### ISSUE TITLE
Cant render chinese character

### ISSUE THREAD

**Issue by tmoonlight** [pofider/phantom-html-to-pdf#93] opened 2018-03-16 05:22 UTC
is there anyway to encode my text?

**Comment by bjrmatos** [comment] 2018-03-16 15:12
hi! i can not give you the exact reason for those characters not being able to render because i don't have enough details about your case but the most general problems is that html is not set to the `utf-8` charset or probably the machine that you are using to render is missing some fonts necessary to support those characters.

some links about it that contain information and past problems similar to your case.

- https://jsreport.net/learn/phantom-pdf#national-characters
- https://forum.jsreport.net/topic/180/japanese-characters-rendering-incorrectly-in-jsreport-online/12
- https://forum.jsreport.net/topic/316/pdf-cannot-display-the-correct-charset-even-utf8-was-set-at-html-meta-tag/3

i'm closing the issue since this is not a bug with the library itself but most related to general phantomjs problem.

**Closed by bjrmatos** 2018-03-16 15:12 UTC

**Comment by tmoonlight** [comment] 2018-03-23 11:54
thanks, that "missing some fonts" is the reason.
