### ISSUE TITLE
Images wont print in the PDF

### ISSUE THREAD

**Issue by alfredoborrero** [pofider/phantom-html-to-pdf#34] opened 2016-08-30 22:18 UTC
I am using "phantom-html-to-pdf" to convert to PDF the HTML output of my process. The HTML has 2 images and they are not printed. Instead i get a rectangle where the image is supposed to be printed and also in a wrong location.
[wrong-output.pdf](https://github.com/pofider/phantom-html-to-pdf/files/446019/wrong-output.pdf)

If i decided to press CTRL-P i can print the HTML output using my PDF Printer without any issue.
[correct-output.pdf](https://github.com/pofider/phantom-html-to-pdf/files/446027/correct-output.pdf)

Is there any reason why you think is doing this? Is there any trick to enable the printing of the images and CSS associated to the HTML?

Regards,

**Comment by bjrmatos** [comment] 2016-08-30 22:21
@alfredoborrero can you post the html source that you are trying to convert? it will be helpful to reproduce the issue.

also, can you give us your OS, node version? thnks!

**Comment by alfredoborrero** [comment] 2016-08-30 22:40
<div id="header">
    <div id="logo">
      <h1><img src="/static/images/novel.jpg" width="100px" height="100px"> Micro Controller Description </h1>
    </div>
  </div>
  <div id="main_info">
    <div id="pin_description_list">
            PinA0:test<br>
            PinA1:test<br>
            PinA2:test<br>
            PinA3:test<br>
            PinA4:test<br>
            PinA5:test<br>
            Pin0:test<br>
            Pin1:test<br>
            Pin2:test<br>
            Pin3:test<br>
            Pin4:test<br>
            Pin5:test<br>
            Pin6:test<br>
            Pin7:test<br>
            Pin8:test<br>
            Pin9:test<br>
            Pin10:test<br>
            Pin11:test<br>
            Pin12:test<br>
            Pin13:test<br>
    </div>
    <div id="imagecontroller">
      <img src="/../../static/droppable/images/Imagenes_Arduino/ArduinoUno_R3_Front.jpg" width="350px" height="500px">
    </div>
  </div>

**Comment by alfredoborrero** [comment] 2016-08-30 22:40
`<div id="header">
    <div id="logo">
      <h1><img src="/static/images/novel.jpg" width="100px" height="100px"> Micro Controller Description </h1>
    </div>
  </div>
  <div id="main_info">
    <div id="pin_description_list">
            PinA0:test<br>
            PinA1:test<br>
            PinA2:test<br>
            PinA3:test<br>
            PinA4:test<br>
            PinA5:test<br>
            Pin0:test<br>
            Pin1:test<br>
            Pin2:test<br>
            Pin3:test<br>
            Pin4:test<br>
            Pin5:test<br>
            Pin6:test<br>
            Pin7:test<br>
            Pin8:test<br>
            Pin9:test<br>
            Pin10:test<br>
            Pin11:test<br>
            Pin12:test<br>
            Pin13:test<br>
    </div>
    <div id="imagecontroller">
      <img src="/../../static/droppable/images/Imagenes_Arduino/ArduinoUno_R3_Front.jpg" width="350px" height="500px">
    </div>
  </div>`

**Comment by alfredoborrero** [comment] 2016-08-30 22:41
The NodeJS version is 4.3.0 and i am using Windows 7

**Comment by bjrmatos** [comment] 2016-08-31 03:31
@alfredoborrero the problem is that you can't reference a local image like that (because of how phantomjs works with local files).

you have two options to make this work.

1.- inline the two images in the html as base64

`<img alt="Embedded Image" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." />`

so you won't have any problems because of path resolution.

2.- request the two images with the `file://` url pointing where your images are in disk

example:

`file:///etc/path/to/my/image/image.jpg`

**Comment by pofider** [comment] 2016-08-31 06:12
Additionally to the second option, you need to also pass `allowLocalFilesAccess:true` See the list of options [here](https://github.com/pofider/phantom-html-to-pdf#local-options). 

You may also consider using html [base tag](http://www.w3schools.com/tags/tag_base.asp) to set the root address to your images and then use just relative paths. 
Or consider exposing images through web server and reference images using `http`.

**Comment by pofider** [comment] 2016-09-01 11:24
Hope this is clear now. Closing.

**Closed by pofider** 2016-09-01 11:24 UTC
