### ISSUE TITLE
error crashes on node server with passenger

### ISSUE THREAD

**Issue by juergengunz** [pofider/phantom-html-to-pdf#84] opened 2017-11-26 17:09 UTC
i am getting following error when using this module
is it possible to make it work without the cluster?

` Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 7176 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:63:12)
App 7176 stderr:     at require (internal/module.js:20:19)
App 7176 stderr:     at Object.<anonymous> (/var/www/vhosts/holmi.at/api.holmi.at/node_modules/phantom-workers/lib/phantomManager.js:12:15)
App 7176 stderr:     at Module._compile (module.js:570:32)
App 7176 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 7176 stderr:     at Module.load (module.js:487:32)
App 7176 stderr:     at tryModuleLoad (module.js:446:12)
App 7176 stderr:     at Function.Module._load (module.js:438:3)
App 7176 stderr:     at Module.require (module.js:497:17)
App 7176 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 7176 stderr:     at require (internal/module.js:20:19)
App 7176 stderr:     at Object.<anonymous> (/var/www/vhosts/holmi.at/api.holmi.at/node_modules/phantom-workers/index.js:6:33)
App 7176 stderr:     at Module._compile (module.js:570:32)
App 7176 stderr:     at Object.Module._extensions..js (module.js:579:10)
App 7176 stderr:     at Module.load (module.js:487:32)
App 7176 stderr:     at tryModuleLoad (module.js:446:12)`

**Comment by pofider** [comment] 2017-11-26 18:28
This is a duplicate of https://github.com/pofider/phantom-workers/issues/14
Please don't waste our time by posting the same multiple times. Thank you

**Closed by pofider** 2017-11-26 18:28 UTC
